theme = "catppuccin_mocha"


[editor]
line-number = "relative"
cursorline = true
color-modes = true
insert-final-newline = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.auto-save]
focus-lost = true

[editor.indent-guides]
character = "â”Š"
render = true
skip-levels = 1

[editor.statusline]
left = [
  "mode",
  "file-name",
  "read-only-indicator",
  "file-modification-indicator",
]
center = ["diagnostics"]
right = ["workspace-diagnostics", "register", "spinner"]
mode.normal = "N"
mode.insert = "I"
mode.select = "S"


[keys.normal]
a = "insert_mode"
A = "insert_at_line_start"
t = "append_mode"
T = "insert_at_line_end"
w = "open_below"
W = "open_above"

o = "move_next_word_start"
O = "move_next_long_word_start"
n = "move_prev_word_start"
N = "move_prev_long_word_start"

pageup = "page_cursor_half_up"
pagedown = "page_cursor_half_down"

r = "replace_with_yanked"
h = "hover"
j = "join_selections"
l = "find_till_char"
L = "till_prev_char"
tab = "goto_last_accessed_file"

C-s = ":wa"
C-q = ":wqa"
C-a = "code_action"
C-f = "file_picker"

F5 = ":config-reload"

[keys.normal.e]
e = "move_prev_word_end"
m = "search_prev"
d = "goto_prev_diag"

[keys.normal.i]
e = "move_next_word_end"
m = "search_next"
d = "goto_prev_diag"
