---
- name: Neovim setup
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Clone git repo
      git:
        repo: 'git@github.com:grig-iv/nvim.git'
        dest: ~/.config/nvim
        update: no

    - name: Install packages
      become: yes
      pacman:
        name: 
          - neovim
          - ripgrep
          - tree-sitter
          - jq
          - nodejs
          - lua-language-server
          - stylua
      
